@startuml
start
   : Admin Provides update Book Method;

   : Admin provides BookIdNo;

if (bookId present) then (yes book present)
    if (book info is null) then (yes)
      : throw exception book info can not be null;
      end;
     else (no not null)

      :set new info Title/Author/PublishYear;
      end;
      endif
else(no book not present)
    : error Message book not found;
    end;

@enduml