@startuml

start
   : Admin Provides Add Method;
if (book or book info is null) then (yes)
    :error message book info can not be null;
    end;
else (no)
    : set book Id no;
    : add book in the list;
    end;
@enduml



@startuml
Admin --> bookApp : input book info


BookApp --> BookService : addBook(Animal n,newAnimal)
AnimalService --> AnimalRepository : getAnimal()
AnimalService <-- AnimalRepository : List<Animal>

alt New Animal already exist In the List
AnimalService --> AnimalShelterApp : return false
user <-- AnimalShelterApp : Sorry Animal already present

else Add new animal in the list
AnimalService --> AnimalService : aanroep add method of list to add new animal
AnimalShelterApp <-- AnimalService : return true
user <-- AnimalShelterApp : animal added

end
@enduml

